InsufficentPermissions: "§4You do not have permission to use this command."
MessagePrefix: "§4§lStealSolo §f§l| "

# in seconds (5 minutes)
MediaCooldown: 300

# don't touch this Raven (will spam the console like a LOT)
debug: false