InsufficentPermissions: "&4You do not have permission to use this command."
MessagePrefix: "&4&lStealSolo &f&l| "

# in seconds (5 minutes)
media:
  # cooldown for each /media usage
  cooldown: 300

  # %player% = player
  # %link% = link
  StreamMessage: "&5Check out %player% on %link% by clicking this message!"
  UploadMessage: "&5Check out a video on %link% from %player% by clicking this message!"
  StreamHoverMessage: "&5Click to watch %link%!"
  UploadHoverMessage: "&5Click to watch %player% at %link%!"
  # only shows when the mouse is over the chat message

paycoins:
    # %player% = command sender
    # %amount% = amount
    # %target% = recipient
  PayMessageSender: "&5You have paid %amount% coins to %target%."
  PayMessageRecipient: "&5You have received %amount% coins from %player%."

moshpit:
  corner1:
    x: 608
    y: 92
    z: -740
    world: "minecraft:overworld"
      # x, y, z, world of the first corner of the moshpit
  corner2:
    x: 622
    y: 82
    z: -754
    world: "minecraft:overworld"
    # x, y, z, world of the moshpit location
  dmg-multiplier: 2
    # damage multiplier for the moshpit

# don't touch this Raven (will spam the console like a LOT)
debug: false